### ISSUE TITLE
async mutators 

### ISSUE THREAD

**Issue by jamiebuilds** [aweary/react-copy-write#19]
If `createMutator` passed the `mutate()` method instead of the `draft` it could better support async

```js
const { createMutator } = createState({
  value: "",
  loading: false,
  error: null,
});

const updateValue = createMutator(async (mutate, value) => {
  mutate(draft => { draft.loading = true; });
  try {
    await fetch('/api/v1/value', { method: 'POST', ... });
    mutate(draft => { draft.value = value; });
  } catch (error) {
    mutate(draft => { draft.error = error; });
  } finally {
    mutate(draft => { draft.loading = false; });
  }
});
```

**Comment by aweary** [comment]
I was thinking that `mutate` could just be returned from `createState` as well. It's actually [currently exported as `update`](https://github.com/aweary/react-copy-write/blob/4b3c870706b185888cd434c623b8116e9e025460/src/index.js#L189) because I changed the name and forgot to remove it (😬). Do you think renaming it `mutate` and documenting it be sufficient?

I wrote `createMutator` because I liked the API of defining a mutator that has the `draft` automatically applied, but that's about the only reason. Exposing `mutate` directly should be safe.

**Comment by jamiebuilds** [comment]
I've been looking at ways to write states w/ their mutators in the same module, that might actually be the best way


**states/counter.js**

```js
import createState from 'react-copy-write';

export type State = {
  count: number
};

export const initialState: State = {
  count: 0
};

// Export Provider, Consumer, wish it wasn't awkward to _not_ export `mutate` (update)
export const { Provider, Consumer, mutate } = createState(initialState);

// mutators:
export function increment() {
  mutate(draft => { draft.count + 1});
}

export function decrement() {
  mutate(draft => { draft.count - 1});
}

// selectors?
export function selectCount(state) {
  return state.count;
}
```

**components/Counter.js**

```js
import { Consumer, increment, decrement, selectCount } from '../states/counter';

export default function Counter(props: {}) {
  return (
    <Consumer selector={selectCount}>
      {count => (
        <>
          <span>{count}</span>
          <button onClick={decrement}>-</button>
          <button onClick={increment}>+</button>
        </>
      )}
    </Consumer>
  );
}
```

**Comment by aweary** [comment]
Cool, I'll rename the `update` export and make a release when I'm back from vacation

**Comment by aweary** [comment]
`mutate` is returned from `createState` now

**Comment by jamiebuilds** [comment]
Do you want to document something like the above pattern/
